domain: laremund.github.io/portfolio-vite/       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://laremund.github.io/portfolio-vite/  # the base hostname and protocol for your site, e.g. http://example.com
# baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder